-- ==============================================================================
-- DU Attend: Fix Cloud Sync, Schedule Overrides & CCSA Roster Migration
-- Run this in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/xczioqwkdzbqadesbvmt/sql/new
-- ==============================================================================

-- 1. Relax foreign key constraints on attendance sessions & records so sync NEVER fails
ALTER TABLE attendance_sessions DROP CONSTRAINT IF EXISTS attendance_sessions_subject_id_fkey;
ALTER TABLE attendance_sessions DROP CONSTRAINT IF EXISTS attendance_sessions_faculty_id_fkey;
ALTER TABLE attendance_records DROP CONSTRAINT IF EXISTS attendance_records_student_id_fkey;
ALTER TABLE attendance_records DROP CONSTRAINT IF EXISTS attendance_records_session_id_fkey;

-- 2. Create schedule_overrides table for class cancellations and rescheduling
CREATE TABLE IF NOT EXISTS schedule_overrides (
  id TEXT PRIMARY KEY,
  timetable_item_id TEXT,
  subject_id TEXT,
  faculty_id TEXT,
  faculty_user_id TEXT,
  faculty_name TEXT,
  action TEXT NOT NULL CHECK (action IN ('cancelled', 'rescheduled')),
  reason TEXT,
  original_day TEXT NOT NULL,
  original_time_slot TEXT NOT NULL,
  new_day_of_week TEXT,
  new_time_slot TEXT,
  new_room TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  active BOOLEAN NOT NULL DEFAULT true
);

-- 3. Enable RLS and permissions on schedule_overrides
ALTER TABLE schedule_overrides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Overrides" ON schedule_overrides;
CREATE POLICY "Public Read Overrides" ON schedule_overrides FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Overrides" ON schedule_overrides;
CREATE POLICY "Public Insert Overrides" ON schedule_overrides FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Overrides" ON schedule_overrides;
CREATE POLICY "Public Update Overrides" ON schedule_overrides FOR UPDATE USING (true);

-- 4. Enable Supabase Realtime for schedule_overrides
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'schedule_overrides'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE schedule_overrides;
  END IF;
END $$;

-- 5. Academic Hierarchy Setup
INSERT INTO universities (id, name) VALUES
  ('university-du', 'Dibrugarh University')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO departments (id, university_id, name) VALUES
  ('department-computer-applications', 'university-du', 'Centre for Computer Science and Applications')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 6. Programmes
INSERT INTO programmes (id, department_id, name) VALUES
  ('programme-bca', 'department-computer-applications', 'Bachelor of Computer Application (BCA)'),
  ('programme-mca', 'department-computer-applications', 'Master of Computer Application (MCA)'),
  ('programme-pgdca', 'department-computer-applications', 'Post Graduate Diploma in Computer Application (PGDCA)')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 7. Semesters
INSERT INTO semesters (id, programme_id, name) VALUES
  ('semester-bca-1', 'programme-bca', 'BCA 1st Semester'),
  ('semester-bca-3', 'programme-bca', 'BCA 3rd Semester'),
  ('semester-bca-5', 'programme-bca', 'BCA 5th Semester'),
  ('semester-mca-1', 'programme-mca', 'MCA 1st Semester'),
  ('semester-mca-3', 'programme-mca', 'MCA 3rd Semester'),
  ('semester-pgdca-1', 'programme-pgdca', 'PGDCA 1st Semester')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 8. Subjects (56 CCSA Subjects)
INSERT INTO subjects (id, code, name, programme_id, semester_id, active) VALUES
  ('subject-pst', 'BCA-101', 'Problem Solving Techniques', 'programme-bca', 'semester-bca-1', true),
  ('subject-computer-fundamentals', 'BCA-102', 'Computer Fundamentals & Applications', 'programme-bca', 'semester-bca-1', true),
  ('subject-mathematics', 'BCA-103', 'Mathematical Foundation of Computer Science - I', 'programme-bca', 'semester-bca-1', true),
  ('subject-english', 'BCA-104', 'English Communication', 'programme-bca', 'semester-bca-1', true),
  ('subject-evs', 'BCA-105', 'Environmental Studies', 'programme-bca', 'semester-bca-1', true),
  ('subject-iks-bca1', 'BCA-106', 'Indian Knowledge System', 'programme-bca', 'semester-bca-1', true),
  ('subject-audit-1', 'BCA-107', 'Audit Course - I', 'programme-bca', 'semester-bca-1', true),
  ('subject-pst-lab', 'BCA-101L', 'Problem Solving Techniques Laboratory', 'programme-bca', 'semester-bca-1', true),
  ('subject-cfa-lab', 'BCA-102L', 'Computer Fundamentals Laboratory', 'programme-bca', 'semester-bca-1', true),
  ('subject-bca3-fla', 'BCA-301', 'Formal Language & Automata', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-os', 'BCA-302', 'Operating Systems', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-os-lab', 'BCA-302L', 'Operating Systems Laboratory', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-iss', 'BCA-303', 'Introduction to Software Security', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-iss-lab', 'BCA-303L', 'Software Security Laboratory', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-se', 'BCA-304', 'Software Engineering', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-se-lab', 'BCA-304L', 'Software Engineering Laboratory', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca3-maths', 'BCA-305', 'Mathematics - III', 'programme-bca', 'semester-bca-3', true),
  ('subject-bca5-or', 'BCA-501', 'Operations Research', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-or-lab', 'BCA-501L', 'Operations Research Laboratory', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-iwp', 'BCA-502', 'Internet & Web Programming', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-iwp-lab', 'BCA-502L', 'Internet & Web Programming Laboratory', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-cc', 'BCA-503', 'Cloud Computing', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-icg', 'BCA-504', 'Introduction to Computer Graphics', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-icg-lab', 'BCA-504L', 'Computer Graphics Laboratory', 'programme-bca', 'semester-bca-5', true),
  ('subject-bca5-minor-project', 'BCA-505', 'Minor Project Work', 'programme-bca', 'semester-bca-5', true),
  ('subject-mca1-latex', 'MCA-101', 'Technical Writing & LaTeX', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-dd', 'MCA-102', 'Digital Design & Architecture', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-dd-lab', 'MCA-102L', 'Digital Design Laboratory', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-oopd', 'MCA-103', 'Object Oriented Programming & Design', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-op', 'MCA-104', 'Optimization Techniques', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-dm', 'MCA-105', 'Discrete Mathematics', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-cpps', 'MCA-107', 'Computer Programming & Problem Solving', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-cpps-lab', 'MCA-107L', 'CPPS Laboratory', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca1-iks', 'MCA-108', 'Indian Knowledge System', 'programme-mca', 'semester-mca-1', true),
  ('subject-mca3-ai', 'MCA-301', 'Artificial Intelligence', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-daa', 'MCA-302', 'Design & Analysis of Algorithms', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-daa-lab', 'MCA-302L', 'DAA Laboratory', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-wt', 'MCA-303', 'Web Technologies', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-wt-lab', 'MCA-303L', 'Web Technologies Laboratory', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-pp', 'MCA-304', 'Python Programming', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-pp-lab', 'MCA-304L', 'Python Programming Laboratory', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-cc', 'MCA-305', 'Cloud Computing', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-dmml', 'MCA-306', 'Data Mining & Machine Learning', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-dmml-lab', 'MCA-306L', 'Data Mining & ML Laboratory', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-se', 'MCA-307', 'Software Engineering', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-se-lab', 'MCA-307L', 'Software Engineering Laboratory', 'programme-mca', 'semester-mca-3', true),
  ('subject-mca3-skill', 'MCA-308', 'Skill Training', 'programme-mca', 'semester-mca-3', true),
  ('subject-pgdca-c', 'PGDCA-101', 'Programming in C', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-c-lab', 'PGDCA-101L', 'C Programming Laboratory', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-dccn', 'PGDCA-102', 'Data Communication & Computer Networks', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-dccn-lab', 'PGDCA-102L', 'DCCN Laboratory', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-fc', 'PGDCA-103', 'Fundamentals of Computers', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-fc-lab', 'PGDCA-103L', 'FC Laboratory', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-rdbms', 'PGDCA-104', 'Relational Database Management Systems', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-rdbms-lab', 'PGDCA-104L', 'RDBMS Laboratory', 'programme-pgdca', 'semester-pgdca-1', true),
  ('subject-pgdca-project', 'PGDCA-105', 'Project Work', 'programme-pgdca', 'semester-pgdca-1', true)
ON CONFLICT (id) DO UPDATE SET code = EXCLUDED.code, name = EXCLUDED.name, active = EXCLUDED.active;

-- 9. Faculty & Generic Instructor
INSERT INTO users (id, role, name, username, active, password) VALUES
  ('user-fac001', 'faculty', 'Course Instructor', 'FAC001', true, 'faculty123'),
  ('user-admin001', 'admin', 'Admin', 'ADMIN001', true, 'admin123')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, active = EXCLUDED.active;

INSERT INTO faculties (id, user_id, faculty_id, active) VALUES
  ('faculty-fac001', 'user-fac001', 'FAC001', true)
ON CONFLICT (id) DO NOTHING;

-- Assign all subjects to default faculty
INSERT INTO faculty_assignments (id, faculty_id, subject_id, active) VALUES
  ('asgn-fac001-0', 'faculty-fac001', 'subject-pst', true),
  ('asgn-fac001-1', 'faculty-fac001', 'subject-computer-fundamentals', true),
  ('asgn-fac001-2', 'faculty-fac001', 'subject-mathematics', true),
  ('asgn-fac001-3', 'faculty-fac001', 'subject-english', true),
  ('asgn-fac001-4', 'faculty-fac001', 'subject-evs', true),
  ('asgn-fac001-5', 'faculty-fac001', 'subject-iks-bca1', true),
  ('asgn-fac001-6', 'faculty-fac001', 'subject-audit-1', true),
  ('asgn-fac001-7', 'faculty-fac001', 'subject-pst-lab', true),
  ('asgn-fac001-8', 'faculty-fac001', 'subject-cfa-lab', true),
  ('asgn-fac001-9', 'faculty-fac001', 'subject-bca3-fla', true),
  ('asgn-fac001-10', 'faculty-fac001', 'subject-bca3-os', true),
  ('asgn-fac001-11', 'faculty-fac001', 'subject-bca3-os-lab', true),
  ('asgn-fac001-12', 'faculty-fac001', 'subject-bca3-iss', true),
  ('asgn-fac001-13', 'faculty-fac001', 'subject-bca3-iss-lab', true),
  ('asgn-fac001-14', 'faculty-fac001', 'subject-bca3-se', true),
  ('asgn-fac001-15', 'faculty-fac001', 'subject-bca3-se-lab', true),
  ('asgn-fac001-16', 'faculty-fac001', 'subject-bca3-maths', true),
  ('asgn-fac001-17', 'faculty-fac001', 'subject-bca5-or', true),
  ('asgn-fac001-18', 'faculty-fac001', 'subject-bca5-or-lab', true),
  ('asgn-fac001-19', 'faculty-fac001', 'subject-bca5-iwp', true),
  ('asgn-fac001-20', 'faculty-fac001', 'subject-bca5-iwp-lab', true),
  ('asgn-fac001-21', 'faculty-fac001', 'subject-bca5-cc', true),
  ('asgn-fac001-22', 'faculty-fac001', 'subject-bca5-icg', true),
  ('asgn-fac001-23', 'faculty-fac001', 'subject-bca5-icg-lab', true),
  ('asgn-fac001-24', 'faculty-fac001', 'subject-bca5-minor-project', true),
  ('asgn-fac001-25', 'faculty-fac001', 'subject-mca1-latex', true),
  ('asgn-fac001-26', 'faculty-fac001', 'subject-mca1-dd', true),
  ('asgn-fac001-27', 'faculty-fac001', 'subject-mca1-dd-lab', true),
  ('asgn-fac001-28', 'faculty-fac001', 'subject-mca1-oopd', true),
  ('asgn-fac001-29', 'faculty-fac001', 'subject-mca1-op', true),
  ('asgn-fac001-30', 'faculty-fac001', 'subject-mca1-dm', true),
  ('asgn-fac001-31', 'faculty-fac001', 'subject-mca1-cpps', true),
  ('asgn-fac001-32', 'faculty-fac001', 'subject-mca1-cpps-lab', true),
  ('asgn-fac001-33', 'faculty-fac001', 'subject-mca1-iks', true),
  ('asgn-fac001-34', 'faculty-fac001', 'subject-mca3-ai', true),
  ('asgn-fac001-35', 'faculty-fac001', 'subject-mca3-daa', true),
  ('asgn-fac001-36', 'faculty-fac001', 'subject-mca3-daa-lab', true),
  ('asgn-fac001-37', 'faculty-fac001', 'subject-mca3-wt', true),
  ('asgn-fac001-38', 'faculty-fac001', 'subject-mca3-wt-lab', true),
  ('asgn-fac001-39', 'faculty-fac001', 'subject-mca3-pp', true),
  ('asgn-fac001-40', 'faculty-fac001', 'subject-mca3-pp-lab', true),
  ('asgn-fac001-41', 'faculty-fac001', 'subject-mca3-cc', true),
  ('asgn-fac001-42', 'faculty-fac001', 'subject-mca3-dmml', true),
  ('asgn-fac001-43', 'faculty-fac001', 'subject-mca3-dmml-lab', true),
  ('asgn-fac001-44', 'faculty-fac001', 'subject-mca3-se', true),
  ('asgn-fac001-45', 'faculty-fac001', 'subject-mca3-se-lab', true),
  ('asgn-fac001-46', 'faculty-fac001', 'subject-mca3-skill', true),
  ('asgn-fac001-47', 'faculty-fac001', 'subject-pgdca-c', true),
  ('asgn-fac001-48', 'faculty-fac001', 'subject-pgdca-c-lab', true),
  ('asgn-fac001-49', 'faculty-fac001', 'subject-pgdca-dccn', true),
  ('asgn-fac001-50', 'faculty-fac001', 'subject-pgdca-dccn-lab', true),
  ('asgn-fac001-51', 'faculty-fac001', 'subject-pgdca-fc', true),
  ('asgn-fac001-52', 'faculty-fac001', 'subject-pgdca-fc-lab', true),
  ('asgn-fac001-53', 'faculty-fac001', 'subject-pgdca-rdbms', true),
  ('asgn-fac001-54', 'faculty-fac001', 'subject-pgdca-rdbms-lab', true),
  ('asgn-fac001-55', 'faculty-fac001', 'subject-pgdca-project', true)
ON CONFLICT (id) DO NOTHING;

-- 10. CCSA Student Users (314 Students)
INSERT INTO users (id, role, name, username, active, password) VALUES
  ('user-bca1-001', 'student', 'Abhigyan Konwar', 'abhigyan', true, 'abhigyan'),
  ('user-bca1-002', 'student', 'Abhipran Subadar', 'abhipran', true, 'abhipran'),
  ('user-bca1-003', 'student', 'Abinash Khatowal', 'abinash', true, 'abinash'),
  ('user-bca1-004', 'student', 'Abiyon Saikia', 'abiyon', true, 'abiyon'),
  ('user-bca1-005', 'student', 'Aditya Kiran Konwar', 'aditya', true, 'aditya'),
  ('user-bca1-006', 'student', 'Ahiron Sarma Baruah', 'ahiron', true, 'ahiron'),
  ('user-bca1-007', 'student', 'Aishwarya Bhuyan', 'aishwarya', true, 'aishwarya'),
  ('user-bca1-008', 'student', 'Akangkhya Medhi', 'akangkhya', true, 'akangkhya'),
  ('user-bca1-009', 'student', 'Anchit Das', 'anchit', true, 'anchit'),
  ('user-bca1-010', 'student', 'Angelina Deori', 'angelina', true, 'angelina'),
  ('user-bca1-011', 'student', 'Anindam Bora', 'anindam', true, 'anindam'),
  ('user-bca1-012', 'student', 'Anmol Singh', 'anmol', true, 'anmol'),
  ('user-bca1-013', 'student', 'Anwesha Chutia', 'anwesha', true, 'anwesha'),
  ('user-bca1-014', 'student', 'Arif Aman Ahmed', 'arif', true, 'arif'),
  ('user-bca1-015', 'student', 'Aruhon Boruah', 'aruhon', true, 'aruhon'),
  ('user-bca1-016', 'student', 'Aryan Gogoi', 'aryan', true, 'aryan'),
  ('user-bca1-017', 'student', 'Asfak Hasmi', 'asfak', true, 'asfak'),
  ('user-bca1-018', 'student', 'Ashish Saud', 'ashish', true, 'ashish'),
  ('user-bca1-019', 'student', 'Ayandeep Das', 'ayandeep', true, 'ayandeep'),
  ('user-bca1-020', 'student', 'Ayesha Yasmeen', 'ayesha', true, 'ayesha'),
  ('user-bca1-021', 'student', 'Ayon Baruah', 'ayon', true, 'ayon'),
  ('user-bca1-022', 'student', 'Ayon Mahajan', 'ayon', true, 'ayon'),
  ('user-bca1-023', 'student', 'Ayush Dey', 'ayush', true, 'ayush'),
  ('user-bca1-024', 'student', 'Ayush Karmakar', 'ayush', true, 'ayush'),
  ('user-bca1-025', 'student', 'Baishnabi Boruah', 'baishnabi', true, 'baishnabi'),
  ('user-bca1-026', 'student', 'Bhahil Das', 'bhahil', true, 'bhahil'),
  ('user-bca1-027', 'student', 'Bibash Das', 'bibash', true, 'bibash'),
  ('user-bca1-028', 'student', 'Bibek Tamang', 'bibek', true, 'bibek'),
  ('user-bca1-029', 'student', 'Binita Purty', 'binita', true, 'binita'),
  ('user-bca1-030', 'student', 'Bishal Karmakar', 'bishal', true, 'bishal'),
  ('user-bca1-031', 'student', 'Bitupan Deka', 'bitupan', true, 'bitupan'),
  ('user-bca1-032', 'student', 'Cathrine Topno', 'cathrine', true, 'cathrine'),
  ('user-bca1-033', 'student', 'Chandan Chetry', 'chandan', true, 'chandan'),
  ('user-bca1-034', 'student', 'Danish Ullah', 'danish', true, 'danish'),
  ('user-bca1-035', 'student', 'Debojit Deb', 'debojit', true, 'debojit'),
  ('user-bca1-036', 'student', 'Dibyadarshan Kalita', 'dibyadarshan', true, 'dibyadarshan'),
  ('user-bca1-037', 'student', 'Dimpal Gogoi', 'dimpal', true, 'dimpal'),
  ('user-bca1-038', 'student', 'Disha Borgohain', 'disha', true, 'disha'),
  ('user-bca1-039', 'student', 'Dorpon Boruah', 'dorpon', true, 'dorpon'),
  ('user-bca1-040', 'student', 'Fanindra Sharma', 'fanindra', true, 'fanindra'),
  ('user-bca1-041', 'student', 'Geetashree Chutia', 'geetashree', true, 'geetashree'),
  ('user-bca1-042', 'student', 'Gorima Handique', 'gorima', true, 'gorima'),
  ('user-bca1-043', 'student', 'Gouri Sankar Chetia', 'gouri', true, 'gouri'),
  ('user-bca1-044', 'student', 'Hrisikesh Rajkonwar', 'hrisikesh', true, 'hrisikesh'),
  ('user-bca1-045', 'student', 'Jaswanta Phukan', 'jaswanta', true, 'jaswanta'),
  ('user-bca1-046', 'student', 'Jenifa Ahmed', 'jenifa', true, 'jenifa'),
  ('user-bca1-047', 'student', 'Junaid Chaudhary', 'junaid', true, 'junaid'),
  ('user-bca1-048', 'student', 'Kartik Pasi', 'kartik', true, 'kartik'),
  ('user-bca1-049', 'student', 'Kasmir Kachari', 'kasmir', true, 'kasmir'),
  ('user-bca1-050', 'student', 'Khanjon Borgohain', 'khanjon', true, 'khanjon'),
  ('user-bca1-051', 'student', 'Khusi Gogoi', 'khusi', true, 'khusi'),
  ('user-bca1-052', 'student', 'Kimonraj Doley', 'kimonraj', true, 'kimonraj'),
  ('user-bca1-053', 'student', 'Kiyan Pegu', 'kiyan', true, 'kiyan'),
  ('user-bca1-054', 'student', 'Kousi Pradhan', 'kousi', true, 'kousi'),
  ('user-bca1-055', 'student', 'Kripa Sundar Bhuyan', 'kripa', true, 'kripa'),
  ('user-bca1-056', 'student', 'Krishnanan Saikia', 'krishnanan', true, 'krishnanan'),
  ('user-bca1-057', 'student', 'Krishtianu Gogoi', 'krishtianu', true, 'krishtianu'),
  ('user-bca1-058', 'student', 'Kriti Saikia', 'kriti', true, 'kriti'),
  ('user-bca1-059', 'student', 'Kuldip Kumar Neog', 'kuldip', true, 'kuldip'),
  ('user-bca1-060', 'student', 'Kunal Bharati', 'kunal', true, 'kunal'),
  ('user-bca1-061', 'student', 'Layad Konwar', 'layad', true, 'layad'),
  ('user-bca1-062', 'student', 'Lord Ripan Dhan', 'lord', true, 'lord'),
  ('user-bca1-063', 'student', 'Lovely Dutta', 'lovely', true, 'lovely'),
  ('user-bca1-064', 'student', 'Luna Gogoi', 'luna', true, 'luna'),
  ('user-bca1-065', 'student', 'Maharnab Phukan', 'maharnab', true, 'maharnab'),
  ('user-bca1-066', 'student', 'Md Fardeen Rahman', 'fardeen', true, 'fardeen'),
  ('user-bca1-067', 'student', 'Miss Sabnam Sultana', 'sabnam', true, 'sabnam'),
  ('user-bca1-068', 'student', 'Nandita Deori', 'nandita', true, 'nandita'),
  ('user-bca1-069', 'student', 'Nibir Junak Boruah', 'nibir', true, 'nibir'),
  ('user-bca1-070', 'student', 'Nirman Nilim Gogoi', 'nirman', true, 'nirman'),
  ('user-bca1-071', 'student', 'Oeishiki Deb', 'oeishiki', true, 'oeishiki'),
  ('user-bca1-072', 'student', 'Padmanav Sarmah', 'padmanav', true, 'padmanav'),
  ('user-bca1-073', 'student', 'Partha Das', 'partha', true, 'partha'),
  ('user-bca1-074', 'student', 'Partha Protim Gogoi', 'partha', true, 'partha'),
  ('user-bca1-075', 'student', 'Pranchi', 'pranchi', true, 'pranchi'),
  ('user-bca1-076', 'student', 'Pranjal Nagbonshi', 'pranjal', true, 'pranjal'),
  ('user-bca1-077', 'student', 'Prince Kumar Loram', 'prince', true, 'prince'),
  ('user-bca1-078', 'student', 'Rajnish Chetia', 'rajnish', true, 'rajnish'),
  ('user-bca1-079', 'student', 'Rashmi Rekha Sutradhar', 'rashmi', true, 'rashmi'),
  ('user-bca1-080', 'student', 'Rimjhim Singpho', 'rimjhim', true, 'rimjhim'),
  ('user-bca1-081', 'student', 'Rimpi Bora', 'rimpi', true, 'rimpi'),
  ('user-bca1-082', 'student', 'Rocktim Nayan Das', 'rocktim', true, 'rocktim'),
  ('user-bca1-083', 'student', 'Rupsikha Deb', 'rupsikha', true, 'rupsikha'),
  ('user-bca1-084', 'student', 'Sagar Pratap Bhaspar', 'sagar', true, 'sagar'),
  ('user-bca1-085', 'student', 'Sahanaj Begum', 'sahanaj', true, 'sahanaj'),
  ('user-bca1-086', 'student', 'Sahinur Mallik', 'sahinur', true, 'sahinur'),
  ('user-bca1-087', 'student', 'Sar Im Rongphar', 'sar', true, 'sar'),
  ('user-bca1-088', 'student', 'Sasanka Bora', 'sasanka', true, 'sasanka'),
  ('user-bca1-089', 'student', 'Satyaraj Das', 'satyaraj', true, 'satyaraj'),
  ('user-bca1-090', 'student', 'Shibani Gogoi', 'shibani', true, 'shibani'),
  ('user-bca1-091', 'student', 'Shilpi Gogoi', 'shilpi', true, 'shilpi'),
  ('user-bca1-092', 'student', 'Shriya Das', 'shriya', true, 'shriya'),
  ('user-bca1-093', 'student', 'Sintu Borgohain', 'sintu', true, 'sintu'),
  ('user-bca1-094', 'student', 'Somayya Tabasum Bora', 'somayya', true, 'somayya'),
  ('user-bca1-095', 'student', 'Somrik Sengupta', 'somrik', true, 'somrik'),
  ('user-bca1-096', 'student', 'Soumyadeep Das', 'soumyadeep', true, 'soumyadeep'),
  ('user-bca1-097', 'student', 'Subrata Dev', 'subrata', true, 'subrata'),
  ('user-bca1-098', 'student', 'Sudipta Gogoi', 'sudipta', true, 'sudipta'),
  ('user-bca1-099', 'student', 'Tushar Singha', 'tushar', true, 'tushar'),
  ('user-bca1-100', 'student', 'Udipta Sonowal', 'udipta', true, 'udipta'),
  ('user-bca1-101', 'student', 'Upakhana Deori', 'upakhana', true, 'upakhana'),
  ('user-bca1-102', 'student', 'Vivek Upadhyaya', 'vivek', true, 'vivek'),
  ('user-bca3-001', 'student', 'Abhishek Gogoi', 'abhishek', true, 'abhishek'),
  ('user-bca3-002', 'student', 'Abhishek Paul', 'abhishek', true, 'abhishek'),
  ('user-bca3-003', 'student', 'Aditya Dowarah', 'aditya', true, 'aditya'),
  ('user-bca3-004', 'student', 'Agarstin Malik Duarte Milton', 'agarstin', true, 'agarstin'),
  ('user-bca3-005', 'student', 'Akash Boruah', 'akash', true, 'akash'),
  ('user-bca3-006', 'student', 'Alongkita Baruah', 'alongkita', true, 'alongkita'),
  ('user-bca3-007', 'student', 'Ananaya Bora', 'ananaya', true, 'ananaya'),
  ('user-bca3-008', 'student', 'Anirban Gogoi', 'anirban', true, 'anirban'),
  ('user-bca3-009', 'student', 'Anishya Gogoi', 'anishya', true, 'anishya'),
  ('user-bca3-010', 'student', 'Ankursri Mahanta', 'ankursri', true, 'ankursri'),
  ('user-bca3-011', 'student', 'Anshuman Bose', 'anshuman', true, 'anshuman'),
  ('user-bca3-012', 'student', 'Ayush Giri', 'ayush', true, 'ayush'),
  ('user-bca3-013', 'student', 'Bitupan Taw', 'bitupan', true, 'bitupan'),
  ('user-bca3-014', 'student', 'Daniel Khakhlary', 'daniel', true, 'daniel'),
  ('user-bca3-015', 'student', 'Deb Doley', 'deb', true, 'deb'),
  ('user-bca3-016', 'student', 'Debasish Bhuyan', 'debasish', true, 'debasish'),
  ('user-bca3-017', 'student', 'Debojit Bora', 'debojit', true, 'debojit'),
  ('user-bca3-018', 'student', 'Diksha Hazarika', 'diksha', true, 'diksha'),
  ('user-bca3-019', 'student', 'Gonesh Sahu', 'gonesh', true, 'gonesh'),
  ('user-bca3-020', 'student', 'Gourovraj Boruah', 'gourovraj', true, 'gourovraj'),
  ('user-bca3-021', 'student', 'Gyan Jyoti Gogoi', 'gyan', true, 'gyan'),
  ('user-bca3-022', 'student', 'Haramohan Sonowal', 'haramohan', true, 'haramohan'),
  ('user-bca3-023', 'student', 'Harshika Jain', 'harshika', true, 'harshika'),
  ('user-bca3-024', 'student', 'Himadriza Phukan', 'himadriza', true, 'himadriza'),
  ('user-bca3-025', 'student', 'Ishani Dutta', 'ishani', true, 'ishani'),
  ('user-bca3-026', 'student', 'Jilmil Borthakur', 'jilmil', true, 'jilmil'),
  ('user-bca3-027', 'student', 'Kabir Boruah', 'kabir', true, 'kabir'),
  ('user-bca3-028', 'student', 'Khusbu Sah', 'khusbu', true, 'khusbu'),
  ('user-bca3-029', 'student', 'Manashee Tanti', 'manashee', true, 'manashee'),
  ('user-bca3-030', 'student', 'Mayuri Panging', 'mayuri', true, 'mayuri'),
  ('user-bca3-031', 'student', 'Md Farhan', 'farhan', true, 'farhan'),
  ('user-bca3-032', 'student', 'Monuj Majumder', 'monuj', true, 'monuj'),
  ('user-bca3-033', 'student', 'Moyuri Phukan', 'moyuri', true, 'moyuri'),
  ('user-bca3-034', 'student', 'Mriduraj Borboruah', 'mriduraj', true, 'mriduraj'),
  ('user-bca3-035', 'student', 'Nikumoni Chutia', 'nikumoni', true, 'nikumoni'),
  ('user-bca3-036', 'student', 'Nisha Doley', 'nisha', true, 'nisha'),
  ('user-bca3-037', 'student', 'Om Saikia', 'om', true, 'om'),
  ('user-bca3-038', 'student', 'Palak Shah', 'palak', true, 'palak'),
  ('user-bca3-039', 'student', 'Palden Tamang', 'palden', true, 'palden'),
  ('user-bca3-040', 'student', 'Piyush Bhadra', 'piyush', true, 'piyush'),
  ('user-bca3-041', 'student', 'Prabal Gohain', 'prabal', true, 'prabal'),
  ('user-bca3-042', 'student', 'Pranoti Sunil Tandale', 'pranoti', true, 'pranoti'),
  ('user-bca3-043', 'student', 'Pratyasha Kakoty', 'pratyasha', true, 'pratyasha'),
  ('user-bca3-044', 'student', 'Priyanganabh Baruah', 'priyanganabh', true, 'priyanganabh'),
  ('user-bca3-045', 'student', 'Priyanka Phookan', 'priyanka', true, 'priyanka'),
  ('user-bca3-046', 'student', 'Rajdeep Gogoi', 'rajdeep', true, 'rajdeep'),
  ('user-bca3-047', 'student', 'Rajdeep Kaushik', 'rajdeep', true, 'rajdeep'),
  ('user-bca3-048', 'student', 'Rimjhim Kumari Shah', 'rimjhim', true, 'rimjhim'),
  ('user-bca3-049', 'student', 'Rishita Dutta', 'rishita', true, 'rishita'),
  ('user-bca3-050', 'student', 'Rubul Gan', 'rubul', true, 'rubul'),
  ('user-bca3-051', 'student', 'Saadat Zameer Rahman', 'saadat', true, 'saadat'),
  ('user-bca3-052', 'student', 'Sahr Emmanuel Morsay', 'sahr', true, 'sahr'),
  ('user-bca3-053', 'student', 'Sanjib Rishi', 'sanjib', true, 'sanjib'),
  ('user-bca3-054', 'student', 'Sanju Pegu', 'sanju', true, 'sanju'),
  ('user-bca3-055', 'student', 'Santipriya Gogoi', 'santipriya', true, 'santipriya'),
  ('user-bca3-056', 'student', 'Satyajit Mondal', 'satyajit', true, 'satyajit'),
  ('user-bca3-057', 'student', 'Somudra Borah', 'somudra', true, 'somudra'),
  ('user-bca3-058', 'student', 'Sudeep Sarkar', 'sudeep', true, 'sudeep'),
  ('user-bca3-059', 'student', 'Sukh Deb Mandal', 'sukh', true, 'sukh'),
  ('user-bca3-060', 'student', 'Suvraj Kashyap', 'suvraj', true, 'suvraj'),
  ('user-bca5-001', 'student', 'Aayushri Hazarika', 'aayushri', true, 'aayushri'),
  ('user-bca5-002', 'student', 'Abhishek Behera', 'abhishek', true, 'abhishek'),
  ('user-bca5-003', 'student', 'Akshita Thapa', 'akshita', true, 'akshita'),
  ('user-bca5-004', 'student', 'Andy Ricardo Deposi', 'andy', true, 'andy'),
  ('user-bca5-005', 'student', 'Aniket Topno', 'aniket', true, 'aniket'),
  ('user-bca5-006', 'student', 'Ankita Kumari', 'ankita', true, 'ankita'),
  ('user-bca5-007', 'student', 'Anuj Rai', 'anuj', true, 'anuj'),
  ('user-bca5-008', 'student', 'Anurag Priyam Chutia', 'anurag', true, 'anurag'),
  ('user-bca5-009', 'student', 'Arijit Sarkar', 'arijit', true, 'arijit'),
  ('user-bca5-010', 'student', 'Arya Borah', 'arya', true, 'arya'),
  ('user-bca5-011', 'student', 'Aryan Sharma', 'aryan', true, 'aryan'),
  ('user-bca5-012', 'student', 'Asish Sahu', 'asish', true, 'asish'),
  ('user-bca5-013', 'student', 'Barbi Gogoi', 'barbi', true, 'barbi'),
  ('user-bca5-014', 'student', 'Bidyot Bikash Boruah', 'bidyot', true, 'bidyot'),
  ('user-bca5-015', 'student', 'Binit Sonowal', 'binit', true, 'binit'),
  ('user-bca5-016', 'student', 'Bondita Boruah', 'bondita', true, 'bondita'),
  ('user-bca5-017', 'student', 'Chanuj Duarah', 'chanuj', true, 'chanuj'),
  ('user-bca5-018', 'student', 'Chenkham Chowlu', 'chenkham', true, 'chenkham'),
  ('user-bca5-019', 'student', 'Chinmoy Sonowal', 'chinmoy', true, 'chinmoy'),
  ('user-bca5-020', 'student', 'Chinnay Mili', 'chinnay', true, 'chinnay'),
  ('user-bca5-021', 'student', 'Debasish Borthakur', 'debasish', true, 'debasish'),
  ('user-bca5-022', 'student', 'Derion Sonowal', 'derion', true, 'derion'),
  ('user-bca5-023', 'student', 'Digbijoy Senapoti', 'digbijoy', true, 'digbijoy'),
  ('user-bca5-024', 'student', 'Drub Namasudra', 'drub', true, 'drub'),
  ('user-bca5-025', 'student', 'Farhana Khanam', 'farhana', true, 'farhana'),
  ('user-bca5-026', 'student', 'Gayatri Saikia', 'gayatri', true, 'gayatri'),
  ('user-bca5-027', 'student', 'Gouri Saikia', 'gouri', true, 'gouri'),
  ('user-bca5-028', 'student', 'Hari Sah', 'hari', true, 'hari'),
  ('user-bca5-029', 'student', 'Harshit Rajguru', 'harshit', true, 'harshit'),
  ('user-bca5-030', 'student', 'Ishpita Chutia', 'ishpita', true, 'ishpita'),
  ('user-bca5-031', 'student', 'Jagannath Baba', 'jagannath', true, 'jagannath'),
  ('user-bca5-032', 'student', 'Jhorna Gogoi', 'jhorna', true, 'jhorna'),
  ('user-bca5-033', 'student', 'Jyotishmoy Barman', 'jyotishmoy', true, 'jyotishmoy'),
  ('user-bca5-034', 'student', 'Luceta Bordoloi', 'luceta', true, 'luceta'),
  ('user-bca5-035', 'student', 'Mehdi Hassan', 'mehdi', true, 'mehdi'),
  ('user-bca5-036', 'student', 'Miss Sheshadree Dasgupta', 'sheshadree', true, 'sheshadree'),
  ('user-bca5-037', 'student', 'Moharnava Gogoi', 'moharnava', true, 'moharnava'),
  ('user-bca5-038', 'student', 'Mousamraj Phukon', 'mousamraj', true, 'mousamraj'),
  ('user-bca5-039', 'student', 'Nabidul Hassan Duha', 'nabidul', true, 'nabidul'),
  ('user-bca5-040', 'student', 'Nikhil Hazarika', 'nikhil', true, 'nikhil'),
  ('user-bca5-041', 'student', 'Nilutpal Saikia Borah', 'nilutpal', true, 'nilutpal'),
  ('user-bca5-042', 'student', 'Nisha Singh', 'nisha', true, 'nisha'),
  ('user-bca5-043', 'student', 'Padma Palash Saud', 'padma', true, 'padma'),
  ('user-bca5-044', 'student', 'Pooja Kalita', 'pooja', true, 'pooja'),
  ('user-bca5-045', 'student', 'Prerona Rajowar', 'prerona', true, 'prerona'),
  ('user-bca5-046', 'student', 'Progyan Boruah', 'progyan', true, 'progyan'),
  ('user-bca5-047', 'student', 'Raman Upadhyaya', 'raman', true, 'raman'),
  ('user-bca5-048', 'student', 'Ravi Sharma', 'ravi', true, 'ravi'),
  ('user-bca5-049', 'student', 'Rishi Raj Sharma', 'rishi', true, 'rishi'),
  ('user-bca5-050', 'student', 'Rishiraj Gorh', 'rishiraj', true, 'rishiraj'),
  ('user-bca5-051', 'student', 'Rohit Thongam', 'rohit', true, 'rohit'),
  ('user-bca5-052', 'student', 'Roktim Taye', 'roktim', true, 'roktim'),
  ('user-bca5-053', 'student', 'Sahista Hussain', 'sahista', true, 'sahista'),
  ('user-bca5-054', 'student', 'Sayantani Mazumder', 'sayantani', true, 'sayantani'),
  ('user-bca5-055', 'student', 'Shubham Kumar Shah', 'shubham', true, 'shubham'),
  ('user-bca5-056', 'student', 'Smeeta Paul', 'smeeta', true, 'smeeta'),
  ('user-bca5-057', 'student', 'Soyonika Gogoi', 'soyonika', true, 'soyonika'),
  ('user-bca5-058', 'student', 'Susmriti Bora', 'susmriti', true, 'susmriti'),
  ('user-bca5-059', 'student', 'Tina Gogoi', 'tina', true, 'tina'),
  ('user-bca5-060', 'student', 'Trishna Saikia', 'trishna', true, 'trishna'),
  ('user-bca5-061', 'student', 'Tudip Keot', 'tudip', true, 'tudip'),
  ('user-bca5-062', 'student', 'Umesh Sahu', 'umesh', true, 'umesh'),
  ('user-mca1-001', 'student', 'Abhilash Bhuyan', 'abhilash', true, 'abhilash'),
  ('user-mca1-002', 'student', 'Abhilash Hazarika', 'abhilash', true, 'abhilash'),
  ('user-mca1-003', 'student', 'Aftab Ansari', 'aftab', true, 'aftab'),
  ('user-mca1-004', 'student', 'Aryaman Saikia', 'aryaman', true, 'aryaman'),
  ('user-mca1-005', 'student', 'Ayush Sharma', 'ayush', true, 'ayush'),
  ('user-mca1-006', 'student', 'Baishali Bhattacharjee', 'baishali', true, 'baishali'),
  ('user-mca1-007', 'student', 'Binayak Upadhyay', 'binayak', true, 'binayak'),
  ('user-mca1-008', 'student', 'Brinchi Gogoi', 'brinchi', true, 'brinchi'),
  ('user-mca1-009', 'student', 'Debabrata Saikia', 'debabrata', true, 'debabrata'),
  ('user-mca1-010', 'student', 'Deep Jyoti Boruah', 'deep', true, 'deep'),
  ('user-mca1-011', 'student', 'Gargi Dutta', 'gargi', true, 'gargi'),
  ('user-mca1-012', 'student', 'Gaurav Dehingia', 'gaurav', true, 'gaurav'),
  ('user-mca1-013', 'student', 'Gyandeep Dehingia', 'gyandeep', true, 'gyandeep'),
  ('user-mca1-014', 'student', 'Hanshika Bhardwaj', 'hanshika', true, 'hanshika'),
  ('user-mca1-015', 'student', 'Janmijoy Borah', 'janmijoy', true, 'janmijoy'),
  ('user-mca1-016', 'student', 'Jeet Sonowal', 'jeet', true, 'jeet'),
  ('user-mca1-017', 'student', 'Karanraj Karmakar', 'karanraj', true, 'karanraj'),
  ('user-mca1-018', 'student', 'Kishor Hazarika', 'kishor', true, 'kishor'),
  ('user-mca1-019', 'student', 'Krishaloy Dutta', 'krishaloy', true, 'krishaloy'),
  ('user-mca1-020', 'student', 'Manash Pratim Gogoi', 'manash', true, 'manash'),
  ('user-mca1-021', 'student', 'Md Bilaluddin Rahman', 'bilaluddin', true, 'bilaluddin'),
  ('user-mca1-022', 'student', 'Mohit Gupta', 'mohit', true, 'mohit'),
  ('user-mca1-023', 'student', 'Mowsomee Hatimuria', 'mowsomee', true, 'mowsomee'),
  ('user-mca1-024', 'student', 'Panchami Sarkar', 'panchami', true, 'panchami'),
  ('user-mca1-025', 'student', 'Phulan Boro', 'phulan', true, 'phulan'),
  ('user-mca1-026', 'student', 'Plabon Jyoti Bora', 'plabon', true, 'plabon'),
  ('user-mca1-027', 'student', 'Pratyush Priyam Borah', 'pratyush', true, 'pratyush'),
  ('user-mca1-028', 'student', 'Pritisha Gogoi', 'pritisha', true, 'pritisha'),
  ('user-mca1-029', 'student', 'Rahul Nath', 'rahul', true, 'rahul'),
  ('user-mca1-030', 'student', 'Rimonjit Saikia', 'rimonjit', true, 'rimonjit'),
  ('user-mca1-031', 'student', 'Runax Changmai', 'runax', true, 'runax'),
  ('user-mca1-032', 'student', 'Samir Ranjan Hazarika', 'samir', true, 'samir'),
  ('user-mca1-033', 'student', 'Sanchita Gogoi', 'sanchita', true, 'sanchita'),
  ('user-mca1-034', 'student', 'Shahil Deori', 'shahil', true, 'shahil'),
  ('user-mca1-035', 'student', 'Wasim Ishaan Ahmed', 'wasim', true, 'wasim'),
  ('user-mca3-001', 'student', 'Abhi Chetri', 'abhi', true, 'abhi'),
  ('user-mca3-002', 'student', 'Aditya Karmakar', 'aditya', true, 'aditya'),
  ('user-mca3-003', 'student', 'Amar Chetry', 'amar', true, 'amar'),
  ('user-mca3-004', 'student', 'Arghajit Saha', 'arghajit', true, 'arghajit'),
  ('user-mca3-005', 'student', 'Artha Jyoti Hazarika', 'artha', true, 'artha'),
  ('user-mca3-006', 'student', 'Bibek Sarkar', 'bibek', true, 'bibek'),
  ('user-mca3-007', 'student', 'Daisy Sonowal', 'daisy', true, 'daisy'),
  ('user-mca3-008', 'student', 'Dhiraj Borah', 'dhiraj', true, 'dhiraj'),
  ('user-mca3-009', 'student', 'Gouri Gayan', 'gouri', true, 'gouri'),
  ('user-mca3-010', 'student', 'Gouri Saikia', 'gouri', true, 'gouri'),
  ('user-mca3-011', 'student', 'Himakhi Bharali', 'himakhi', true, 'himakhi'),
  ('user-mca3-012', 'student', 'John Jason Opiyo', 'john', true, 'john'),
  ('user-mca3-013', 'student', 'Juman Das', 'juman', true, 'juman'),
  ('user-mca3-014', 'student', 'Kalyan Kumar Gupta', 'kalyan', true, 'kalyan'),
  ('user-mca3-015', 'student', 'Manakh Gohain', 'manakh', true, 'manakh'),
  ('user-mca3-016', 'student', 'Manash Jyoti Baruah', 'manash', true, 'manash'),
  ('user-mca3-017', 'student', 'Mehar Sultana', 'mehar', true, 'mehar'),
  ('user-mca3-018', 'student', 'Mridu Moloy Saikia', 'mridu', true, 'mridu'),
  ('user-mca3-019', 'student', 'Mrinali Borah', 'mrinali', true, 'mrinali'),
  ('user-mca3-020', 'student', 'Nirajnil Dutta', 'nirajnil', true, 'nirajnil'),
  ('user-mca3-021', 'student', 'Niyar Mukuta Dutta', 'niyar', true, 'niyar'),
  ('user-mca3-022', 'student', 'Praduniya Pran Konwar', 'praduniya', true, 'praduniya'),
  ('user-mca3-023', 'student', 'Princi Dutta', 'princi', true, 'princi'),
  ('user-mca3-024', 'student', 'Raja Thakur', 'raja', true, 'raja'),
  ('user-mca3-025', 'student', 'Rupam Phukan', 'rupam', true, 'rupam'),
  ('user-mca3-026', 'student', 'Sahil Zamal Saikia', 'sahil', true, 'sahil'),
  ('user-mca3-027', 'student', 'Sarfaraz Parvez Haque', 'sarfaraz', true, 'sarfaraz'),
  ('user-mca3-028', 'student', 'Shyamal Handique', 'shyamal', true, 'shyamal'),
  ('user-mca3-029', 'student', 'Sororphy Hongray', 'sororphy', true, 'sororphy'),
  ('user-mca3-030', 'student', 'Srishti Mallick', 'srishti', true, 'srishti'),
  ('user-mca3-031', 'student', 'Ummidul Anjar Bin Altab', 'ummidul', true, 'ummidul'),
  ('user-mca3-032', 'student', 'Yanjan Agarwal', 'yanjan', true, 'yanjan'),
  ('user-pgdca1-001', 'student', 'Alakesh Borah', 'alakesh', true, 'alakesh'),
  ('user-pgdca1-002', 'student', 'Ananta Tanti', 'ananta', true, 'ananta'),
  ('user-pgdca1-003', 'student', 'Angika Dehingia', 'angika', true, 'angika'),
  ('user-pgdca1-004', 'student', 'Ankita Bhowmick', 'ankita', true, 'ankita'),
  ('user-pgdca1-005', 'student', 'Babli Sautal', 'babli', true, 'babli'),
  ('user-pgdca1-006', 'student', 'Bipasha Kakoty', 'bipasha', true, 'bipasha'),
  ('user-pgdca1-007', 'student', 'Borsharani Boruah', 'borsharani', true, 'borsharani'),
  ('user-pgdca1-008', 'student', 'Dikshita Phukan', 'dikshita', true, 'dikshita'),
  ('user-pgdca1-009', 'student', 'Drenlee Das', 'drenlee', true, 'drenlee'),
  ('user-pgdca1-010', 'student', 'Gourav Gohain', 'gourav', true, 'gourav'),
  ('user-pgdca1-011', 'student', 'Gyanjyoti Boruah', 'gyanjyoti', true, 'gyanjyoti'),
  ('user-pgdca1-012', 'student', 'Iblina Gogoi', 'iblina', true, 'iblina'),
  ('user-pgdca1-013', 'student', 'Islan Rahman', 'islan', true, 'islan'),
  ('user-pgdca1-014', 'student', 'Jahnabi Boro', 'jahnabi', true, 'jahnabi'),
  ('user-pgdca1-015', 'student', 'Jayanta Boruah', 'jayanta', true, 'jayanta'),
  ('user-pgdca1-016', 'student', 'Kankana Baishya', 'kankana', true, 'kankana'),
  ('user-pgdca1-017', 'student', 'Kironjyoti Saikia', 'kironjyoti', true, 'kironjyoti'),
  ('user-pgdca1-018', 'student', 'Nikhita Gogoi', 'nikhita', true, 'nikhita'),
  ('user-pgdca1-019', 'student', 'Pritom Konwar', 'pritom', true, 'pritom'),
  ('user-pgdca1-020', 'student', 'Rina Chutia', 'rina', true, 'rina'),
  ('user-pgdca1-021', 'student', 'Rittika Singh', 'rittika', true, 'rittika'),
  ('user-pgdca1-022', 'student', 'Roshmi Borgohain', 'roshmi', true, 'roshmi'),
  ('user-pgdca1-023', 'student', 'Uttara Konwar', 'uttara', true, 'uttara')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, username = EXCLUDED.username, password = EXCLUDED.password;

-- 11. CCSA Students
INSERT INTO students (id, user_id, student_id, programme_id, semester_id, active) VALUES
  ('student-bca1-001', 'user-bca1-001', 'BCA1-001', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-002', 'user-bca1-002', 'BCA1-002', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-003', 'user-bca1-003', 'BCA1-003', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-004', 'user-bca1-004', 'BCA1-004', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-005', 'user-bca1-005', 'BCA1-005', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-006', 'user-bca1-006', 'BCA1-006', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-007', 'user-bca1-007', 'BCA1-007', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-008', 'user-bca1-008', 'BCA1-008', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-009', 'user-bca1-009', 'BCA1-009', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-010', 'user-bca1-010', 'BCA1-010', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-011', 'user-bca1-011', 'BCA1-011', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-012', 'user-bca1-012', 'BCA1-012', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-013', 'user-bca1-013', 'BCA1-013', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-014', 'user-bca1-014', 'BCA1-014', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-015', 'user-bca1-015', 'BCA1-015', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-016', 'user-bca1-016', 'BCA1-016', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-017', 'user-bca1-017', 'BCA1-017', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-018', 'user-bca1-018', 'BCA1-018', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-019', 'user-bca1-019', 'BCA1-019', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-020', 'user-bca1-020', 'BCA1-020', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-021', 'user-bca1-021', 'BCA1-021', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-022', 'user-bca1-022', 'BCA1-022', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-023', 'user-bca1-023', 'BCA1-023', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-024', 'user-bca1-024', 'BCA1-024', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-025', 'user-bca1-025', 'BCA1-025', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-026', 'user-bca1-026', 'BCA1-026', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-027', 'user-bca1-027', 'BCA1-027', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-028', 'user-bca1-028', 'BCA1-028', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-029', 'user-bca1-029', 'BCA1-029', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-030', 'user-bca1-030', 'BCA1-030', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-031', 'user-bca1-031', 'BCA1-031', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-032', 'user-bca1-032', 'BCA1-032', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-033', 'user-bca1-033', 'BCA1-033', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-034', 'user-bca1-034', 'BCA1-034', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-035', 'user-bca1-035', 'BCA1-035', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-036', 'user-bca1-036', 'BCA1-036', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-037', 'user-bca1-037', 'BCA1-037', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-038', 'user-bca1-038', 'BCA1-038', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-039', 'user-bca1-039', 'BCA1-039', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-040', 'user-bca1-040', 'BCA1-040', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-041', 'user-bca1-041', 'BCA1-041', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-042', 'user-bca1-042', 'BCA1-042', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-043', 'user-bca1-043', 'BCA1-043', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-044', 'user-bca1-044', 'BCA1-044', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-045', 'user-bca1-045', 'BCA1-045', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-046', 'user-bca1-046', 'BCA1-046', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-047', 'user-bca1-047', 'BCA1-047', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-048', 'user-bca1-048', 'BCA1-048', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-049', 'user-bca1-049', 'BCA1-049', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-050', 'user-bca1-050', 'BCA1-050', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-051', 'user-bca1-051', 'BCA1-051', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-052', 'user-bca1-052', 'BCA1-052', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-053', 'user-bca1-053', 'BCA1-053', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-054', 'user-bca1-054', 'BCA1-054', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-055', 'user-bca1-055', 'BCA1-055', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-056', 'user-bca1-056', 'BCA1-056', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-057', 'user-bca1-057', 'BCA1-057', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-058', 'user-bca1-058', 'BCA1-058', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-059', 'user-bca1-059', 'BCA1-059', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-060', 'user-bca1-060', 'BCA1-060', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-061', 'user-bca1-061', 'BCA1-061', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-062', 'user-bca1-062', 'BCA1-062', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-063', 'user-bca1-063', 'BCA1-063', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-064', 'user-bca1-064', 'BCA1-064', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-065', 'user-bca1-065', 'BCA1-065', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-066', 'user-bca1-066', 'BCA1-066', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-067', 'user-bca1-067', 'BCA1-067', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-068', 'user-bca1-068', 'BCA1-068', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-069', 'user-bca1-069', 'BCA1-069', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-070', 'user-bca1-070', 'BCA1-070', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-071', 'user-bca1-071', 'BCA1-071', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-072', 'user-bca1-072', 'BCA1-072', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-073', 'user-bca1-073', 'BCA1-073', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-074', 'user-bca1-074', 'BCA1-074', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-075', 'user-bca1-075', 'BCA1-075', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-076', 'user-bca1-076', 'BCA1-076', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-077', 'user-bca1-077', 'BCA1-077', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-078', 'user-bca1-078', 'BCA1-078', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-079', 'user-bca1-079', 'BCA1-079', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-080', 'user-bca1-080', 'BCA1-080', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-081', 'user-bca1-081', 'BCA1-081', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-082', 'user-bca1-082', 'BCA1-082', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-083', 'user-bca1-083', 'BCA1-083', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-084', 'user-bca1-084', 'BCA1-084', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-085', 'user-bca1-085', 'BCA1-085', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-086', 'user-bca1-086', 'BCA1-086', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-087', 'user-bca1-087', 'BCA1-087', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-088', 'user-bca1-088', 'BCA1-088', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-089', 'user-bca1-089', 'BCA1-089', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-090', 'user-bca1-090', 'BCA1-090', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-091', 'user-bca1-091', 'BCA1-091', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-092', 'user-bca1-092', 'BCA1-092', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-093', 'user-bca1-093', 'BCA1-093', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-094', 'user-bca1-094', 'BCA1-094', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-095', 'user-bca1-095', 'BCA1-095', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-096', 'user-bca1-096', 'BCA1-096', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-097', 'user-bca1-097', 'BCA1-097', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-098', 'user-bca1-098', 'BCA1-098', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-099', 'user-bca1-099', 'BCA1-099', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-100', 'user-bca1-100', 'BCA1-100', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-101', 'user-bca1-101', 'BCA1-101', 'programme-bca', 'semester-bca-1', true),
  ('student-bca1-102', 'user-bca1-102', 'BCA1-102', 'programme-bca', 'semester-bca-1', true),
  ('student-bca3-001', 'user-bca3-001', 'BCA3-001', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-002', 'user-bca3-002', 'BCA3-002', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-003', 'user-bca3-003', 'BCA3-003', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-004', 'user-bca3-004', 'BCA3-004', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-005', 'user-bca3-005', 'BCA3-005', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-006', 'user-bca3-006', 'BCA3-006', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-007', 'user-bca3-007', 'BCA3-007', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-008', 'user-bca3-008', 'BCA3-008', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-009', 'user-bca3-009', 'BCA3-009', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-010', 'user-bca3-010', 'BCA3-010', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-011', 'user-bca3-011', 'BCA3-011', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-012', 'user-bca3-012', 'BCA3-012', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-013', 'user-bca3-013', 'BCA3-013', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-014', 'user-bca3-014', 'BCA3-014', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-015', 'user-bca3-015', 'BCA3-015', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-016', 'user-bca3-016', 'BCA3-016', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-017', 'user-bca3-017', 'BCA3-017', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-018', 'user-bca3-018', 'BCA3-018', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-019', 'user-bca3-019', 'BCA3-019', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-020', 'user-bca3-020', 'BCA3-020', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-021', 'user-bca3-021', 'BCA3-021', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-022', 'user-bca3-022', 'BCA3-022', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-023', 'user-bca3-023', 'BCA3-023', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-024', 'user-bca3-024', 'BCA3-024', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-025', 'user-bca3-025', 'BCA3-025', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-026', 'user-bca3-026', 'BCA3-026', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-027', 'user-bca3-027', 'BCA3-027', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-028', 'user-bca3-028', 'BCA3-028', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-029', 'user-bca3-029', 'BCA3-029', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-030', 'user-bca3-030', 'BCA3-030', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-031', 'user-bca3-031', 'BCA3-031', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-032', 'user-bca3-032', 'BCA3-032', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-033', 'user-bca3-033', 'BCA3-033', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-034', 'user-bca3-034', 'BCA3-034', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-035', 'user-bca3-035', 'BCA3-035', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-036', 'user-bca3-036', 'BCA3-036', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-037', 'user-bca3-037', 'BCA3-037', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-038', 'user-bca3-038', 'BCA3-038', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-039', 'user-bca3-039', 'BCA3-039', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-040', 'user-bca3-040', 'BCA3-040', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-041', 'user-bca3-041', 'BCA3-041', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-042', 'user-bca3-042', 'BCA3-042', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-043', 'user-bca3-043', 'BCA3-043', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-044', 'user-bca3-044', 'BCA3-044', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-045', 'user-bca3-045', 'BCA3-045', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-046', 'user-bca3-046', 'BCA3-046', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-047', 'user-bca3-047', 'BCA3-047', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-048', 'user-bca3-048', 'BCA3-048', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-049', 'user-bca3-049', 'BCA3-049', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-050', 'user-bca3-050', 'BCA3-050', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-051', 'user-bca3-051', 'BCA3-051', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-052', 'user-bca3-052', 'BCA3-052', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-053', 'user-bca3-053', 'BCA3-053', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-054', 'user-bca3-054', 'BCA3-054', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-055', 'user-bca3-055', 'BCA3-055', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-056', 'user-bca3-056', 'BCA3-056', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-057', 'user-bca3-057', 'BCA3-057', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-058', 'user-bca3-058', 'BCA3-058', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-059', 'user-bca3-059', 'BCA3-059', 'programme-bca', 'semester-bca-3', true),
  ('student-bca3-060', 'user-bca3-060', 'BCA3-060', 'programme-bca', 'semester-bca-3', true),
  ('student-bca5-001', 'user-bca5-001', 'BCA5-001', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-002', 'user-bca5-002', 'BCA5-002', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-003', 'user-bca5-003', 'BCA5-003', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-004', 'user-bca5-004', 'BCA5-004', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-005', 'user-bca5-005', 'BCA5-005', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-006', 'user-bca5-006', 'BCA5-006', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-007', 'user-bca5-007', 'BCA5-007', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-008', 'user-bca5-008', 'BCA5-008', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-009', 'user-bca5-009', 'BCA5-009', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-010', 'user-bca5-010', 'BCA5-010', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-011', 'user-bca5-011', 'BCA5-011', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-012', 'user-bca5-012', 'BCA5-012', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-013', 'user-bca5-013', 'BCA5-013', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-014', 'user-bca5-014', 'BCA5-014', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-015', 'user-bca5-015', 'BCA5-015', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-016', 'user-bca5-016', 'BCA5-016', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-017', 'user-bca5-017', 'BCA5-017', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-018', 'user-bca5-018', 'BCA5-018', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-019', 'user-bca5-019', 'BCA5-019', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-020', 'user-bca5-020', 'BCA5-020', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-021', 'user-bca5-021', 'BCA5-021', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-022', 'user-bca5-022', 'BCA5-022', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-023', 'user-bca5-023', 'BCA5-023', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-024', 'user-bca5-024', 'BCA5-024', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-025', 'user-bca5-025', 'BCA5-025', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-026', 'user-bca5-026', 'BCA5-026', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-027', 'user-bca5-027', 'BCA5-027', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-028', 'user-bca5-028', 'BCA5-028', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-029', 'user-bca5-029', 'BCA5-029', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-030', 'user-bca5-030', 'BCA5-030', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-031', 'user-bca5-031', 'BCA5-031', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-032', 'user-bca5-032', 'BCA5-032', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-033', 'user-bca5-033', 'BCA5-033', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-034', 'user-bca5-034', 'BCA5-034', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-035', 'user-bca5-035', 'BCA5-035', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-036', 'user-bca5-036', 'BCA5-036', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-037', 'user-bca5-037', 'BCA5-037', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-038', 'user-bca5-038', 'BCA5-038', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-039', 'user-bca5-039', 'BCA5-039', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-040', 'user-bca5-040', 'BCA5-040', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-041', 'user-bca5-041', 'BCA5-041', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-042', 'user-bca5-042', 'BCA5-042', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-043', 'user-bca5-043', 'BCA5-043', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-044', 'user-bca5-044', 'BCA5-044', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-045', 'user-bca5-045', 'BCA5-045', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-046', 'user-bca5-046', 'BCA5-046', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-047', 'user-bca5-047', 'BCA5-047', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-048', 'user-bca5-048', 'BCA5-048', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-049', 'user-bca5-049', 'BCA5-049', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-050', 'user-bca5-050', 'BCA5-050', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-051', 'user-bca5-051', 'BCA5-051', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-052', 'user-bca5-052', 'BCA5-052', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-053', 'user-bca5-053', 'BCA5-053', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-054', 'user-bca5-054', 'BCA5-054', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-055', 'user-bca5-055', 'BCA5-055', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-056', 'user-bca5-056', 'BCA5-056', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-057', 'user-bca5-057', 'BCA5-057', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-058', 'user-bca5-058', 'BCA5-058', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-059', 'user-bca5-059', 'BCA5-059', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-060', 'user-bca5-060', 'BCA5-060', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-061', 'user-bca5-061', 'BCA5-061', 'programme-bca', 'semester-bca-5', true),
  ('student-bca5-062', 'user-bca5-062', 'BCA5-062', 'programme-bca', 'semester-bca-5', true),
  ('student-mca1-001', 'user-mca1-001', 'MCA1-001', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-002', 'user-mca1-002', 'MCA1-002', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-003', 'user-mca1-003', 'MCA1-003', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-004', 'user-mca1-004', 'MCA1-004', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-005', 'user-mca1-005', 'MCA1-005', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-006', 'user-mca1-006', 'MCA1-006', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-007', 'user-mca1-007', 'MCA1-007', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-008', 'user-mca1-008', 'MCA1-008', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-009', 'user-mca1-009', 'MCA1-009', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-010', 'user-mca1-010', 'MCA1-010', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-011', 'user-mca1-011', 'MCA1-011', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-012', 'user-mca1-012', 'MCA1-012', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-013', 'user-mca1-013', 'MCA1-013', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-014', 'user-mca1-014', 'MCA1-014', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-015', 'user-mca1-015', 'MCA1-015', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-016', 'user-mca1-016', 'MCA1-016', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-017', 'user-mca1-017', 'MCA1-017', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-018', 'user-mca1-018', 'MCA1-018', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-019', 'user-mca1-019', 'MCA1-019', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-020', 'user-mca1-020', 'MCA1-020', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-021', 'user-mca1-021', 'MCA1-021', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-022', 'user-mca1-022', 'MCA1-022', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-023', 'user-mca1-023', 'MCA1-023', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-024', 'user-mca1-024', 'MCA1-024', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-025', 'user-mca1-025', 'MCA1-025', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-026', 'user-mca1-026', 'MCA1-026', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-027', 'user-mca1-027', 'MCA1-027', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-028', 'user-mca1-028', 'MCA1-028', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-029', 'user-mca1-029', 'MCA1-029', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-030', 'user-mca1-030', 'MCA1-030', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-031', 'user-mca1-031', 'MCA1-031', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-032', 'user-mca1-032', 'MCA1-032', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-033', 'user-mca1-033', 'MCA1-033', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-034', 'user-mca1-034', 'MCA1-034', 'programme-mca', 'semester-mca-1', true),
  ('student-mca1-035', 'user-mca1-035', 'MCA1-035', 'programme-mca', 'semester-mca-1', true),
  ('student-mca3-001', 'user-mca3-001', 'MCA3-001', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-002', 'user-mca3-002', 'MCA3-002', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-003', 'user-mca3-003', 'MCA3-003', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-004', 'user-mca3-004', 'MCA3-004', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-005', 'user-mca3-005', 'MCA3-005', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-006', 'user-mca3-006', 'MCA3-006', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-007', 'user-mca3-007', 'MCA3-007', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-008', 'user-mca3-008', 'MCA3-008', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-009', 'user-mca3-009', 'MCA3-009', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-010', 'user-mca3-010', 'MCA3-010', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-011', 'user-mca3-011', 'MCA3-011', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-012', 'user-mca3-012', 'MCA3-012', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-013', 'user-mca3-013', 'MCA3-013', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-014', 'user-mca3-014', 'MCA3-014', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-015', 'user-mca3-015', 'MCA3-015', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-016', 'user-mca3-016', 'MCA3-016', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-017', 'user-mca3-017', 'MCA3-017', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-018', 'user-mca3-018', 'MCA3-018', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-019', 'user-mca3-019', 'MCA3-019', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-020', 'user-mca3-020', 'MCA3-020', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-021', 'user-mca3-021', 'MCA3-021', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-022', 'user-mca3-022', 'MCA3-022', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-023', 'user-mca3-023', 'MCA3-023', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-024', 'user-mca3-024', 'MCA3-024', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-025', 'user-mca3-025', 'MCA3-025', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-026', 'user-mca3-026', 'MCA3-026', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-027', 'user-mca3-027', 'MCA3-027', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-028', 'user-mca3-028', 'MCA3-028', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-029', 'user-mca3-029', 'MCA3-029', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-030', 'user-mca3-030', 'MCA3-030', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-031', 'user-mca3-031', 'MCA3-031', 'programme-mca', 'semester-mca-3', true),
  ('student-mca3-032', 'user-mca3-032', 'MCA3-032', 'programme-mca', 'semester-mca-3', true),
  ('student-pgdca1-001', 'user-pgdca1-001', 'PGDCA1-001', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-002', 'user-pgdca1-002', 'PGDCA1-002', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-003', 'user-pgdca1-003', 'PGDCA1-003', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-004', 'user-pgdca1-004', 'PGDCA1-004', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-005', 'user-pgdca1-005', 'PGDCA1-005', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-006', 'user-pgdca1-006', 'PGDCA1-006', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-007', 'user-pgdca1-007', 'PGDCA1-007', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-008', 'user-pgdca1-008', 'PGDCA1-008', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-009', 'user-pgdca1-009', 'PGDCA1-009', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-010', 'user-pgdca1-010', 'PGDCA1-010', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-011', 'user-pgdca1-011', 'PGDCA1-011', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-012', 'user-pgdca1-012', 'PGDCA1-012', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-013', 'user-pgdca1-013', 'PGDCA1-013', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-014', 'user-pgdca1-014', 'PGDCA1-014', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-015', 'user-pgdca1-015', 'PGDCA1-015', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-016', 'user-pgdca1-016', 'PGDCA1-016', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-017', 'user-pgdca1-017', 'PGDCA1-017', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-018', 'user-pgdca1-018', 'PGDCA1-018', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-019', 'user-pgdca1-019', 'PGDCA1-019', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-020', 'user-pgdca1-020', 'PGDCA1-020', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-021', 'user-pgdca1-021', 'PGDCA1-021', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-022', 'user-pgdca1-022', 'PGDCA1-022', 'programme-pgdca', 'semester-pgdca-1', true),
  ('student-pgdca1-023', 'user-pgdca1-023', 'PGDCA1-023', 'programme-pgdca', 'semester-pgdca-1', true)
ON CONFLICT (id) DO UPDATE SET student_id = EXCLUDED.student_id, programme_id = EXCLUDED.programme_id, semester_id = EXCLUDED.semester_id;

-- 12. Ensure Public Access for App Clients
DROP POLICY IF EXISTS "Public Read All" ON users;
CREATE POLICY "Public Read All" ON users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read All" ON students;
CREATE POLICY "Public Read All" ON students FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read All" ON subjects;
CREATE POLICY "Public Read All" ON subjects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read All" ON enrollments;
CREATE POLICY "Public Read All" ON enrollments FOR SELECT USING (true);
